In [2]:
from tensorflow.keras.preprocessing.text import one_hot 

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4238, 8977, 5727, 2014],
 [4238, 8977, 5727, 7071],
 [4238, 9983, 5727, 3006],
 [8170, 3842, 9692, 2717, 1329],
 [8170, 3842, 9692, 2717, 6720],
 [3221, 4238, 4253, 5727, 4592],
 [7410, 6323, 7681, 2717]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4238 8977 5727 2014]
 [   0    0    0    0 4238 8977 5727 7071]
 [   0    0    0    0 4238 9983 5727 3006]
 [   0    0    0 8170 3842 9692 2717 1329]
 [   0    0    0 8170 3842 9692 2717 6720]
 [   0    0    0 3221 4238 4253 5727 4592]
 [   0    0    0    0 7410 6323 7681 2717]]


In [30]:
embedded_docs.shape

(7, 8)

In [9]:
## feature representation
dim=10

In [31]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim, input_length=sent_length))
model.compile('adam','mse')

c:\Users\shind\anaconda3\envs\rnn_env\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [32]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step


array([[[-0.03580076,  0.03355644, -0.00797443,  0.0376482 ,
         -0.02888887,  0.04616712, -0.00389697, -0.03403341,
         -0.01889423,  0.00624876],
        [-0.03580076,  0.03355644, -0.00797443,  0.0376482 ,
         -0.02888887,  0.04616712, -0.00389697, -0.03403341,
         -0.01889423,  0.00624876],
        [-0.03580076,  0.03355644, -0.00797443,  0.0376482 ,
         -0.02888887,  0.04616712, -0.00389697, -0.03403341,
         -0.01889423,  0.00624876],
        [-0.03580076,  0.03355644, -0.00797443,  0.0376482 ,
         -0.02888887,  0.04616712, -0.00389697, -0.03403341,
         -0.01889423,  0.00624876],
        [-0.02843596,  0.04666362,  0.04798919,  0.02416768,
         -0.03540695, -0.04938414,  0.04983166,  0.01236014,
          0.03909803,  0.02664008],
        [ 0.01669348, -0.01576809,  0.0335498 ,  0.02554944,
         -0.02161509,  0.00726069,  0.039616  ,  0.03025774,
         -0.00054724, -0.04114505],
        [-0.03395728, -0.03514604, -0.02305362, -0.0

In [34]:
embedded_docs[0]

array([   0,    0,    0,    0, 4238, 8977, 5727, 2014])

In [33]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step


array([[ 0.04882908, -0.04662802, -0.04017226, -0.04190784,  0.03974006,
        -0.02346172, -0.00829871, -0.02110295, -0.01312363,  0.01093229],
       [ 0.04882908, -0.04662802, -0.04017226, -0.04190784,  0.03974006,
        -0.02346172, -0.00829871, -0.02110295, -0.01312363,  0.01093229],
       [ 0.04882908, -0.04662802, -0.04017226, -0.04190784,  0.03974006,
        -0.02346172, -0.00829871, -0.02110295, -0.01312363,  0.01093229],
       [ 0.04882908, -0.04662802, -0.04017226, -0.04190784,  0.03974006,
        -0.02346172, -0.00829871, -0.02110295, -0.01312363,  0.01093229],
       [-0.00383984, -0.01743995,  0.04560534,  0.03156985, -0.02042522,
         0.03006916,  0.04091854,  0.0416644 , -0.00109323, -0.041925  ],
       [ 0.02855061, -0.01796603,  0.02273135, -0.04236976, -0.02663144,
         0.04025164,  0.04077759, -0.00074799, -0.00471935,  0.02672619],
       [ 0.01025949,  0.00819718,  0.02514053, -0.0058585 , -0.01496582,
        -0.02548078,  0.00640634,  0.03701906